=== 5smug/Data-Schemes-and-applications/Individual Work/submission_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
 <!-- 
    ==================================================================
    This is the schema for the individual xml submission file. 
    See 99999999.xml for a valid example instance. 
    Ensure your [student_no].xml is validated against this schema 
    using Oxygen or some other validator.
    DO NOT EDIT OR CHANGE THIS FILE UNDER ANY CIRCUMSTANCES 
    
    Version 1.5
    ==================================================================
  -->
    <xs:element name="submission_xml">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="group">
                    <xs:complexType>
                        <xs:attribute name="id" use="required" type="group_idType"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="student">
                    <xs:complexType>
                        <xs:attribute name="id" use="required" type="student_idType"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="group_contribution" maxOccurs="1" type="txtType"/>
				<xs:element name="individual_component" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="description" type="txtType"/>
                            <xs:element name="problems" type="txtType"/>
                            <xs:element name="solutions" type="txtType"/>
                            <xs:element name="hours_effort" type="hours_effortType"/>
                            <xs:element name="technologies">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tech" minOccurs="2" maxOccurs="6"
                                            type="techType"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="source_files">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="file" minOccurs="1" maxOccurs="4">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="name" type="xs:string"/>
                                                  <xs:element name="purpose" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="type" use="required" type="cmpType"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="security_discussion" maxOccurs="1" type="txtType"/>
                <xs:element name="individual_comment" maxOccurs="1" type="txtType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="techType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="php"/>
            <xs:enumeration value="xml"/>
            <xs:enumeration value="xslt"/>
            <xs:enumeration value="xsd"/>
            <xs:enumeration value="sql"/>
            <xs:enumeration value="html5"/>
            <xs:enumeration value="css"/>
            <xs:enumeration value="javascript"/>
            <xs:enumeration value="mysql"/>
            <xs:enumeration value="json"/>
            <xs:enumeration value="er-modelling"/>
        	<xs:enumeration value="rss"/>
            <xs:enumeration value="other"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="group_idType">
        <xs:restriction base="xs:string">
        	<xs:enumeration value="A"/>
        	<xs:enumeration value="B"/>
        	<xs:enumeration value="C"/>
        	<xs:enumeration value="D"/>
        	<xs:enumeration value="E"/>
        	<xs:enumeration value="F"/>
        	<xs:enumeration value="G"/>
        	<xs:enumeration value="H"/>
        	<xs:enumeration value="I"/>
        	<xs:enumeration value="J"/>
        	<xs:enumeration value="K"/>
        	<xs:enumeration value="L"/>
        	<xs:enumeration value="M"/>
        	<xs:enumeration value="O"/>
        	<xs:enumeration value="P"/>
        	<xs:enumeration value="Q"/>
        	<xs:enumeration value="R"/>
        	<xs:enumeration value="S"/>
        	<xs:enumeration value="T"/>
        	<xs:enumeration value="U"/>
        	<xs:enumeration value="V"/>
        	<xs:enumeration value="Z"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="student_idType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="23016312"/>
            <xs:enumeration value="23036206"/>
            <xs:enumeration value="24022783"/>
            <xs:enumeration value="23031806"/>
            <xs:enumeration value="23026724"/>
            <xs:enumeration value="21017116"/>
            <xs:enumeration value="24029917"/>
            <xs:enumeration value="23032886"/>
            <xs:enumeration value="23010967"/>
            <xs:enumeration value="24012100"/>
            <xs:enumeration value="24018695"/>
            <xs:enumeration value="23026650"/>
            <xs:enumeration value="23002244"/>
            <xs:enumeration value="20007323"/>
            <xs:enumeration value="24028358"/>
            <xs:enumeration value="21034937"/>
            <xs:enumeration value="24028985"/>
            <xs:enumeration value="24061851"/>
            <xs:enumeration value="24049853"/>
            <xs:enumeration value="24063062"/>
            <xs:enumeration value="24063060"/>
            <xs:enumeration value="23019506"/>
            <xs:enumeration value="24027098"/>
            <xs:enumeration value="23061828"/>
            <xs:enumeration value="24043316"/>
            <xs:enumeration value="23024137"/>
            <xs:enumeration value="23011792"/>
            <xs:enumeration value="24064407"/>
            <xs:enumeration value="24057499"/>
            <xs:enumeration value="23072050"/>
            <xs:enumeration value="24009026"/>
            <xs:enumeration value="24035481"/>
            <xs:enumeration value="24046371"/>
            <xs:enumeration value="24013871"/>
            <xs:enumeration value="23066631"/>
            <xs:enumeration value="24044286"/>
            <xs:enumeration value="24022483"/>
            <xs:enumeration value="22032393"/>
            <xs:enumeration value="23040332"/>
            <xs:enumeration value="23077470"/>
            <xs:enumeration value="24014279"/>
            <xs:enumeration value="24062938"/>
            <xs:enumeration value="23079035"/>
            <xs:enumeration value="23048237"/>
            <xs:enumeration value="24035460"/>
            <xs:enumeration value="22028231"/>
            <xs:enumeration value="22029495"/>
            <xs:enumeration value="23026741"/>
            <xs:enumeration value="23018364"/>
            <xs:enumeration value="23039643"/>
            <xs:enumeration value="24016391"/>
            <xs:enumeration value="24064214"/>
            <xs:enumeration value="24030667"/>
            <xs:enumeration value="22067002"/>
            <xs:enumeration value="23081317"/>
            <xs:enumeration value="24063298"/>
            <xs:enumeration value="24056836"/>
            <xs:enumeration value="24033689"/>
            <xs:enumeration value="24057257"/>
            <xs:enumeration value="21005000"/>
            <xs:enumeration value="24033655"/>
            <xs:enumeration value="23064697"/>
            <xs:enumeration value="24049987"/>
            <xs:enumeration value="24041197"/>
            <xs:enumeration value="24023644"/>
            <xs:enumeration value="24056602"/>
            <xs:enumeration value="24023211"/>
            <xs:enumeration value="24058709"/>
            <xs:enumeration value="24030009"/>
            <xs:enumeration value="23054011"/>
            <xs:enumeration value="23002240"/>
            <xs:enumeration value="24041677"/>
            <xs:enumeration value="23061396"/>
            <xs:enumeration value="23057547"/>
            <xs:enumeration value="24020551"/>
            <xs:enumeration value="24062115"/>
            <xs:enumeration value="23077626"/>
            <xs:enumeration value="99999999"/>            
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="cmpType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Refactor the data set using XML and XML-Schema"/>
            <xs:enumeration value="Build and integrate a comments widget"/>
            <xs:enumeration value="Build and integrate a photo widget"/>
            <xs:enumeration value="Document the code and the system"/>
            <xs:enumeration value="Refactor the front-end to be responsive"/>
            <xs:enumeration value="Refactor the data and map it to a NoSQL database"/>
            <xs:enumeration value="Refactor the application to a (micro) PHP framework"/>
            <xs:enumeration value="Refactor the application to a Single Page Application (SPA)"/>
            <xs:enumeration value="Use and Document a Test Framework"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="txtType">
        <xs:restriction base="xs:string">
            <xs:minLength value="140"/>
            <xs:maxLength value="12000"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="hours_effortType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="120"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>
<!-- DSA Individual Schema File, 2025/26-->
<!-- author: prakash.chatterjee@uwe.ac.uk -->

=== 5smug/Data-Schemes-and-applications/Individual Work/23036206.xml
<?xml version="1.0" encoding="UTF-8"?>
<submission_xml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="submission_schema.xsd">
    <!-- 
    This file is an example of a valid individual submission file. 
    Note the schema file (XSD) pointed to on line 2/3 - TREAT THE SCHEMA AS READ ONLY
    Use this example file as a template and fill with your own data 
    validating as you go along using Oxygen or some other schema aware editor;
	an on-line tool is here: https://www.liquid-technologies.com/online-xsd-validator
    
    DO NOT CHANGE ANY TAGS OR THEIR ORDER BUT ONLY THE CONTENT, OTHERWISE VALIDATION WILL FAIL
    Keep the schema in the same directory as the document as that's where oXygen expects it.
    -->    
    <group id="L"/>
    <student id="23036206"/>
    <!--- Describe one or more group tasks that you contributed to -->
    <group_contribution>
        I contributed to Component 1 by helping design the ER models used for the database. 
        I worked with the group to identify the main entities such as cities and places of interest,
        decideon their attributes, and plan the relationships between them. I also helped plan the SQL
        layout for the database tables so the data could be organised and queried efficiently in MySQL. 
        In addition, I supported the RSS feature by helping with the rss.php file and assisting with how 
        the data from the database would be retrieved and structured into an RSS feed for the application.
     </group_contribution>
    <!--- Describe your individual component -->
    <individual_component type="Refactor the front-end to be responsive">
        <description>
            My part was to refactor the front-end to make the application more responsive across various screen sizes,
            so that the pages would be easier to use on mobile, tablet, and desktop without changing the main functionality of the website,
            such as the navigation bar, map sections, weather sections, places of interest cards, and general spacing, including the styling
            so that the content could adjust better depending on the width of the screen, using responsive CSS rules, and improving how 
            sections were displayed when the screen became smaller, making the interface clearer, more organised, and easier
            for the user to interact with.
        </description>
        <problems>  
            One of the main challenges was adapting the existing layout so that it worked 
            correctly on different screen sizes. Some elements did not align properly when 
            viewed on smaller devices, and certain components needed to be reorganised 
            using responsive grid systems. Another issue was ensuring that styling from 
            the new CSS framework did not conflict with the existing styles in the project. 
        </problems>
        <solutions> 
            These problems were solved by restructuring the layout using the responsive 
            grid system provided by the CSS framework. Media queries and responsive 
            classes were applied to adjust the layout depending on the screen size. 
            Conflicting styles were resolved by reviewing the CSS structure and applying 
            consistent styling rules across the application.
        </solutions>
        <hours_effort>12</hours_effort>
        <technologies>
            <tech>php</tech>
            <tech>html5</tech>
        </technologies>
        <source_files>
            <file>
                <name>index.php</name>
                <purpose>Main page where Bootstrap classes were applied to create a responsive layout</purpose>
            </file>
            <file>
                <name>style.css</name>
                <purpose>Custom styling used alongside the CSS framework to improve the design</purpose>
            </file>
        </source_files>
        
    </individual_component>
    
    <security_discussion> 
        External data sources and web-based technologies required security considerations,
        and malformed XML files had to be validated to ensure that they were not processed.
        Server-side scripts should always be validated and sanitised to reduce risks of injection attacks,
        and access permissions and secure data handling practices should ensure that sensitive information
        is handled securely and that the system operates safely. 
        
        Data security is an important consideration when developing web applications. 
        The Parkerian Hexad identifies six attributes that define information security. 
        In the development of our group application, several of these attributes were 
        considered, particularly in relation to the refactoring of the front-end to 
        create a responsive and accessible user interface.
        
        Confidentiality refers to protecting information from unauthorised access. 
        While the responsive front-end mainly focuses on user interface design, it 
        still plays a role in protecting sensitive information by ensuring that data 
        is displayed appropriately across different devices. Responsive layouts help 
        prevent sensitive content from being accidentally exposed or displayed 
        incorrectly on smaller screens, which could otherwise make information easier 
        to view by unintended users.
        
        Integrity ensures that information remains accurate and is not modified in an 
        unauthorised way. In the application, integrity can be supported through proper 
        input validation and structured data handling. When refactoring the front-end, 
        form elements and user inputs were organised using consistent layout structures, 
        helping to ensure that data entered by users follows the expected format before 
        being processed by the system.
        
       
       Another component of the Parkerian Hexad is availability, and rebuilding the front-end to
       be responsive can make the software available on a variety of devices, such as desktop computers,
       tablets, and mobile phones, thereby increasing availability, and also improving usability and performance
       by ensuring that the software loads properly and operates effectively on a variety of screen sizes.
        
        By considering these aspects of the Parkerian Hexad during development, the 
        application becomes more secure, reliable, and accessible to users across 
        multiple platforms.
    </security_discussion>
    <individual_comment> 
        For this section, you completed this portion of the project individually and refactored the front-end of the
        application to make it responsive and enhance the user interface, which gave me a deeper understanding of responsive
        web design and how CSS frameworks can be used to create flexible layouts that respond to various screen sizes, as well
        as practical experience in optimizing the usability of a website, structuring the pages, and ensuring that the application
        delivers a consistent user experience across desktop, tablet, and mobile platforms
       
     </individual_comment> 
</submission_xml>
<!-- DSA Individual XML File Example, 2025-6 -->
<!-- author: prakash.chatterjee@uwe.ac.uk -->

=== 5smug/Data-Schemes-and-applications/Individual Work/Mohamed Abdillahi.xml
<?xml version="1.0" encoding="UTF-8"?>
<submission_xml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="submission_schema.xsd">
    
    <group id="Z"/>
    <student id="99999999"/>
    
    <!--- Describe one or more group tasks that you contributed to -->
    <group_contribution>
        I contributed to the group project by refactoring the front-end of the application 
        to make it responsive across different screen sizes. I applied a CSS framework to 
        improve the layout, styling, and overall user experience of the website. This 
        included restructuring the page layout, improving navigation, and ensuring that 
        the interface worked well on both desktop and mobile devices.  I supported other group members by reviewing parts 
        of the implementation and assisting with tasks where needed to ensure the project 
        progressed smoothly.
    </group_contribution>
    
    <!--- Describe your individual component -->
    <individual_component type="Refactor the data set using XML and XML-Schema">
        <description>
            My individual task was to refactor the front-end of the application to make it 
            responsive and improve the overall user interface. I applied a CSS framework 
            to enhance the design, layout, and usability of the website. This involved 
            restructuring the page layout, improving the navigation, and ensuring that the 
            website adapts correctly to different screen sizes such as desktops, tablets, 
            and mobile devices. I also used additional tools such as icon libraries to 
            improve the visual appearance of the application.
        </description>
        
        <problems>
            One of the main challenges was adapting the existing layout so that it worked 
            correctly on different screen sizes. Some elements did not align properly when 
            viewed on smaller devices, and certain components needed to be reorganised 
            using responsive grid systems. Another issue was ensuring that styling from 
            the new CSS framework did not conflict with the existing styles in the project.
        </problems>
        
        <solutions>
            These problems were solved by restructuring the layout using the responsive 
            grid system provided by the CSS framework. Media queries and responsive 
            classes were applied to adjust the layout depending on the screen size. 
            Conflicting styles were resolved by reviewing the CSS structure and applying 
            consistent styling rules across the application.
        </solutions>
        
        <hours_effort>12</hours_effort>
        
        <technologies>
            <tech>php</tech>
            <tech>javascript</tech>
            <tech>xml</tech>
        </technologies>
        
        <source_files>
            <file>
                <name>index.html</name>
                <purpose>Main page where Bootstrap classes were applied to create a responsive layout</purpose>
            </file>
            <file>
                <name>style.css</name>
                <purpose>Custom styling used alongside the CSS framework to improve the design</purpose>
            </file>
        </source_files>
        
        
    </individual_component>
    
    <security_discussion>
        Security considerations were important when handling external data sources and web-based 
        technologies. Proper validation of XML files was necessary to prevent malformed data from 
        being processed. Additionally, input validation and sanitisation should be implemented in 
        server-side scripts to reduce risks such as injection attacks. Access permissions and 
        secure data handling practices are also important to ensure that sensitive information 
        is protected and that the system operates safely.
        
        Data security is an important consideration when developing web applications. 
        The Parkerian Hexad identifies six attributes that define information security. 
        In the development of our group application, several of these attributes were 
        considered, particularly in relation to the refactoring of the front-end to 
        create a responsive and accessible user interface.
        
        Confidentiality refers to protecting information from unauthorised access. 
        While the responsive front-end mainly focuses on user interface design, it 
        still plays a role in protecting sensitive information by ensuring that data 
        is displayed appropriately across different devices. Responsive layouts help 
        prevent sensitive content from being accidentally exposed or displayed 
        incorrectly on smaller screens, which could otherwise make information easier 
        to view by unintended users.
        
        Integrity ensures that information remains accurate and is not modified in an 
        unauthorised way. In the application, integrity can be supported through proper 
        input validation and structured data handling. When refactoring the front-end, 
        form elements and user inputs were organised using consistent layout structures, 
        helping to ensure that data entered by users follows the expected format before 
        being processed by the system.
        
        Authenticity refers to verifying that users and data sources are genuine. 
        Although authentication mechanisms are typically handled on the server side, 
        the front-end still contributes by clearly presenting login forms, navigation, 
        and user interface elements that help users interact with the system correctly. 
        A well-structured and responsive interface reduces the risk of user confusion 
        and helps ensure that users interact with legitimate parts of the application.
        
        Availability is another important attribute of the Parkerian Hexad. By 
        refactoring the front-end to be responsive, the application becomes accessible 
        across a wide range of devices, including mobile phones, tablets, and desktop 
        computers. This improves availability because users can access and use the 
        system regardless of the device they are using. Responsive design also improves 
        performance and usability, ensuring that the application loads correctly and 
        remains functional across different screen sizes.
        
        By considering these aspects of the Parkerian Hexad during development, the 
        application becomes more secure, reliable, and accessible to users across 
        multiple platforms.
         
       
        
    </security_discussion>
    
    <individual_comment>
        This part of the project was completed individually and focused on refactoring the 
        front-end of the application to make it responsive and improve the overall user 
        interface. Through this task, I developed a better understanding of responsive web 
        design and how CSS frameworks can be used to create flexible layouts that adapt 
        to different screen sizes. I also gained practical experience in improving website 
        usability, organising page structure, and ensuring that the application provides a 
        consistent user experience across desktop, tablet, and mobile devices.
    </individual_comment>
    
</submission_xml>
