=== 5smug/Data-Schemes-and-applications/Individual Work/submission_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
 <!-- 
    ==================================================================
    This is the schema for the individual xml submission file. 
    See 99999999.xml for a valid example instance. 
    Ensure your [student_no].xml is validated against this schema 
    using Oxygen or some other validator.
    DO NOT EDIT OR CHANGE THIS FILE UNDER ANY CIRCUMSTANCES 
    
    Version 1.5
    ==================================================================
  -->
    <xs:element name="submission_xml">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="group">
                    <xs:complexType>
                        <xs:attribute name="id" use="required" type="group_idType"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="student">
                    <xs:complexType>
                        <xs:attribute name="id" use="required" type="student_idType"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="group_contribution" maxOccurs="1" type="txtType"/>
				<xs:element name="individual_component" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="description" type="txtType"/>
                            <xs:element name="problems" type="txtType"/>
                            <xs:element name="solutions" type="txtType"/>
                            <xs:element name="hours_effort" type="hours_effortType"/>
                            <xs:element name="technologies">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tech" minOccurs="2" maxOccurs="6"
                                            type="techType"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="source_files">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="file" minOccurs="1" maxOccurs="4">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="name" type="xs:string"/>
                                                  <xs:element name="purpose" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="type" use="required" type="cmpType"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="security_discussion" maxOccurs="1" type="txtType"/>
                <xs:element name="individual_comment" maxOccurs="1" type="txtType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="techType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="php"/>
            <xs:enumeration value="xml"/>
            <xs:enumeration value="xslt"/>
            <xs:enumeration value="xsd"/>
            <xs:enumeration value="sql"/>
            <xs:enumeration value="html5"/>
            <xs:enumeration value="css"/>
            <xs:enumeration value="javascript"/>
            <xs:enumeration value="mysql"/>
            <xs:enumeration value="json"/>
            <xs:enumeration value="er-modelling"/>
        	<xs:enumeration value="rss"/>
            <xs:enumeration value="other"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="group_idType">
        <xs:restriction base="xs:string">
        	<xs:enumeration value="A"/>
        	<xs:enumeration value="B"/>
        	<xs:enumeration value="C"/>
        	<xs:enumeration value="D"/>
        	<xs:enumeration value="E"/>
        	<xs:enumeration value="F"/>
        	<xs:enumeration value="G"/>
        	<xs:enumeration value="H"/>
        	<xs:enumeration value="I"/>
        	<xs:enumeration value="J"/>
        	<xs:enumeration value="K"/>
        	<xs:enumeration value="L"/>
        	<xs:enumeration value="M"/>
        	<xs:enumeration value="O"/>
        	<xs:enumeration value="P"/>
        	<xs:enumeration value="Q"/>
        	<xs:enumeration value="R"/>
        	<xs:enumeration value="S"/>
        	<xs:enumeration value="T"/>
        	<xs:enumeration value="U"/>
        	<xs:enumeration value="V"/>
        	<xs:enumeration value="Z"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="student_idType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="23016312"/>
            <xs:enumeration value="23036206"/>
            <xs:enumeration value="24022783"/>
            <xs:enumeration value="23031806"/>
            <xs:enumeration value="23026724"/>
            <xs:enumeration value="21017116"/>
            <xs:enumeration value="24029917"/>
            <xs:enumeration value="23032886"/>
            <xs:enumeration value="23010967"/>
            <xs:enumeration value="24012100"/>
            <xs:enumeration value="24018695"/>
            <xs:enumeration value="23026650"/>
            <xs:enumeration value="23002244"/>
            <xs:enumeration value="20007323"/>
            <xs:enumeration value="24028358"/>
            <xs:enumeration value="21034937"/>
            <xs:enumeration value="24028985"/>
            <xs:enumeration value="24061851"/>
            <xs:enumeration value="24049853"/>
            <xs:enumeration value="24063062"/>
            <xs:enumeration value="24063060"/>
            <xs:enumeration value="23019506"/>
            <xs:enumeration value="24027098"/>
            <xs:enumeration value="23061828"/>
            <xs:enumeration value="24043316"/>
            <xs:enumeration value="23024137"/>
            <xs:enumeration value="23011792"/>
            <xs:enumeration value="24064407"/>
            <xs:enumeration value="24057499"/>
            <xs:enumeration value="23072050"/>
            <xs:enumeration value="24009026"/>
            <xs:enumeration value="24035481"/>
            <xs:enumeration value="24046371"/>
            <xs:enumeration value="24013871"/>
            <xs:enumeration value="23066631"/>
            <xs:enumeration value="24044286"/>
            <xs:enumeration value="24022483"/>
            <xs:enumeration value="22032393"/>
            <xs:enumeration value="23040332"/>
            <xs:enumeration value="23077470"/>
            <xs:enumeration value="24014279"/>
            <xs:enumeration value="24062938"/>
            <xs:enumeration value="23079035"/>
            <xs:enumeration value="23048237"/>
            <xs:enumeration value="24035460"/>
            <xs:enumeration value="22028231"/>
            <xs:enumeration value="22029495"/>
            <xs:enumeration value="23026741"/>
            <xs:enumeration value="23018364"/>
            <xs:enumeration value="23039643"/>
            <xs:enumeration value="24016391"/>
            <xs:enumeration value="24064214"/>
            <xs:enumeration value="24030667"/>
            <xs:enumeration value="22067002"/>
            <xs:enumeration value="23081317"/>
            <xs:enumeration value="24063298"/>
            <xs:enumeration value="24056836"/>
            <xs:enumeration value="24033689"/>
            <xs:enumeration value="24057257"/>
            <xs:enumeration value="21005000"/>
            <xs:enumeration value="24033655"/>
            <xs:enumeration value="23064697"/>
            <xs:enumeration value="24049987"/>
            <xs:enumeration value="24041197"/>
            <xs:enumeration value="24023644"/>
            <xs:enumeration value="24056602"/>
            <xs:enumeration value="24023211"/>
            <xs:enumeration value="24058709"/>
            <xs:enumeration value="24030009"/>
            <xs:enumeration value="23054011"/>
            <xs:enumeration value="23002240"/>
            <xs:enumeration value="24041677"/>
            <xs:enumeration value="23061396"/>
            <xs:enumeration value="23057547"/>
            <xs:enumeration value="24020551"/>
            <xs:enumeration value="24062115"/>
            <xs:enumeration value="23077626"/>
            <xs:enumeration value="99999999"/>            
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="cmpType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Refactor the data set using XML and XML-Schema"/>
            <xs:enumeration value="Build and integrate a comments widget"/>
            <xs:enumeration value="Build and integrate a photo widget"/>
            <xs:enumeration value="Document the code and the system"/>
            <xs:enumeration value="Refactor the front-end to be responsive"/>
            <xs:enumeration value="Refactor the data and map it to a NoSQL database"/>
            <xs:enumeration value="Refactor the application to a (micro) PHP framework"/>
            <xs:enumeration value="Refactor the application to a Single Page Application (SPA)"/>
            <xs:enumeration value="Use and Document a Test Framework"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="txtType">
        <xs:restriction base="xs:string">
            <xs:minLength value="140"/>
            <xs:maxLength value="12000"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="hours_effortType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="120"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>
<!-- DSA Individual Schema File, 2025/26-->
<!-- author: prakash.chatterjee@uwe.ac.uk -->

=== 5smug/Data-Schemes-and-applications/Individual Work/2403368.xml
<?xml version="1.0" encoding="UTF-8"?>
<submission_xml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="submission_schema.xsd">
    <!-- 
    This file is an example of a valid individual submission file. 
    Note the schema file (XSD) pointed to on line 2/3 - TREAT THE SCHEMA AS READ ONLY
    Use this example file as a template and fill with your own data 
    validating as you go along using Oxygen or some other schema aware editor;
	an on-line tool is here: https://www.liquid-technologies.com/online-xsd-validator
    
    DO NOT CHANGE ANY TAGS OR THEIR ORDER BUT ONLY THE CONTENT, OTHERWISE VALIDATION WILL FAIL
    Keep the schema in the same directory as the document as that's where oXygen expects it.
    -->    
    <group id="L"/>
    <student id="2403368"/>
    <!--- Describe one or more group tasks that you contributed to -->
    <group_contribution>
        For the entire group, I have contributed to point 2. Use and integration of external API's, part 3. Configuration file and the logical er model.
        Being in a group of 3 people, we tried to divide the work equally, but it was pretty difficult to do that, especially when not everyone knew how to use 
        sql to create a database, or creating php files. I have more experience using front-end and creating sql's so I took most of the coding & sql parts.
    </group_contribution>
    <!--- Describe your individual component -->
    <individual_component type="Document the code and the system">
        <description>
            While creating most of the code, and even going through files which I haven't created, I have mapped out what each
            sequence does from that part of the code. Although I haven't put explanations everywhere, as in I didn't say for 
            javascript, every php file has deep details for it.
        </description>
        <problems>
            I have encountered problems when creating the weather.php file as it was kinda a new thing for me.
            The problems were relatively normal, as in the API key wasn't connecting, it wasn't gathering the correct
            information. And finally, it wouldn't find the coordinates
        </problems>
        <solutions>
            The solution were that instead of trying to read the API Key, instead, I made it only for config.php so that the
            weather.php file summon it and connect to it. And I also made it so that it gathers the correct information 
            by making it directly connect to places_of_interestID from the database. Finally, to fix the final issue,
            I made it to gathered the lat and lon specifically from the database.
        </solutions>
        <hours_effort>20</hours_effort>
        <technologies>
            <tech>php</tech>
            <tech>javascript & CSS</tech>
            <tech>xml</tech>
        </technologies>
        <source_files>
            <file>
                <name>weather.php</name>
                <purpose>To fetch and summon all weather criteria.</purpose>
            </file>
            <file>
                <name>index.php</name>
                <purpose>Main page. It's got both of the maps and weather forecast, but it does not have the places of interest. Those are for their own pages</purpose>
            </file>
        </source_files>
    </individual_component>
    <security_discussion>
        For our twin cities website, we have considered some of the Parkerian Hexad attributes. One of them is confidentiality. We have decided to not implement a 
        login / logout system. We have decided this for only one truthful reason. We didn't see fit for it. We have implement multiple things that wasn't asked of us,
        but we did not see any reason to add a login / logout system. This would have made our life harder and there's no point in it. As for our API keys,
        we decided to make them server-side that they don't become a hazard to us. This way the APIs aren't exposed, and we can use them whenever we press "F5" to run
        the code. For even further protection, we are 100% sure that all of our database information and even all the work that we've done is saved and completely 
        untouchable on our Github repository. This is being said because we have made our repository private, meaning only the three of us which have created this code 
        can access it, modify it and save it. The contributors are just the three people present in "group L". So not only is our github fully protected, so it's our
        website when we run it. Being run by localhost it truly means no external access can penetrate or invade our project.

        As in for our integrity, all the information displayed on this project is read-only. We do not have any way for user to generate content, or to input it in any way.
        Not only can the users not generate content, the data shown is also read-only. The data presented on the project cannot be modified or tampered with in any way by
        any visitors. Even using localhost to publish it, when public, the website cannot be modified in any way. The foreign keys in our database prevent any type of 
        corruption and makes the localhost a completely safe space to work in and use. For our final integrity check, we have made sure that all our PDO statements
        prevent any type of SQL injection. This was made as the last line of backup to make sure nothing can be edited.

        For our authenticity, we have gathered all the information from public sources, such as OpenWeatherAPI, wikipedia, tourism sites, and others. From OpenWeatherAPI,
        we have gathered all the necessary information for the humidity and weather forecast status. All this information is stored on their part, we get all of this 
        information for simply using their free generated weather_api_key. All the city information, as in coordinates and postcode has been gathered from wikipedia and
        google search engine. As in for information for the description of each individual place, we have gathered that from the tourism website of each individual city.
        We also have our limitations. For example : Flickr. Flickr limits us on our sample images. We knew this and yet we still decided to use because it's a great 
        api to use.

        As for the final security discussion, we can talk about our availability. Database will always automatically start is the XAMPP and the php files are running.
        This meaning that the project is limited because of the localhost limitations. But even with this, if our weather_api_key falls offline, we have a fallback data until 
        it starts running again. And even then, we do have our RSS feed as an alternative access method.
    </security_discussion>
    <individual_comment>
        My main contributions was in setting up the structure and the weather side of the coding side. For how I found it, I can't really say it was easy. But, I can say
        that it challenged me and taught me some stuff. I haven't really worked with php in this volume before. So my attitude towards this coding language has changed, for
        both better and worse. If I were to choose the most difficult part, it would definitely be integrating the javascript with the php code. I have struggled the most
        at that part of the code and I have been working with javascript for more than 3 years. But even with this experience I have made multiple errors with it, dozen even. 
        Those mistakes made my code crash multiple times and just a few days ago I got it figured out. Honestly, just those 150-200 lines of coding cause me more trouble 
        than the MySQL. Creating the database for the information we require was pretty tough, but at least I had the conceptual and logical component as my go to for 
        inspiration and what we needed. I haven't really gave much stress about learning php. It wasn't hard learning the basics of php, more of a journey I could say. 
        Just 2 tutorials and w3schools was enough to help me get started on this project.
    </individual_comment>
</submission_xml>
<!-- DSA Individual XML File Example, 2025-6 -->
<!-- author: prakash.chatterjee@uwe.ac.uk -->

=== 5smug/Data-Schemes-and-applications/Individual Work/24023644.xml
<?xml version="1.0" encoding="UTF-8"?>
<submission_xml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="submission_schema.xsd">
    <!-- 
    This file is an example of a valid individual submission file. 
    Note the schema file (XSD) pointed to on line 2/3 - TREAT THE SCHEMA AS READ ONLY
    Use this example file as a template and fill with your own data 
    validating as you go along using Oxygen or some other schema aware editor;
	an on-line tool is here: https://www.liquid-technologies.com/online-xsd-validator
    
    DO NOT CHANGE ANY TAGS OR THEIR ORDER BUT ONLY THE CONTENT, OTHERWISE VALIDATION WILL FAIL
    Keep the schema in the same directory as the document as that's where oXygen expects it.
    -->    
    <group id="Z"/>
    <student id="99999999"/>
    <!--- Describe one or more group tasks that you contributed to -->
    <group_contribution>
		Sed eu nunc ipsum, nec suscipit lectus. Quisque quis nibh at sem dictum pretium. 
        Pellentesque augue mauris, lobortis vel elementum quis, consequat tempor felis. 
        Sed eu nunc ipsum, nec suscipit lectus. Quisque quis nibh at sem dictum  pretium. 
        Pellentesque augue mauris, lobortis vel elementum quis, consequat tempor felis. .... 
     </group_contribution>
    <!--- Describe your individual component -->
    <individual_component type="Refactor the data set using XML and XML-Schema">
        <description>Sed eu nunc ipsum, nec suscipit lectus. Quisque quis nibh at sem dictum pretium. 
            Pellentesque augue mauris, lobortis vel elementum quis, consequat tempor felis. 
            Sed eu nunc ipsum, nec suscipit lectus. Quisque quis nibh at sem dictum  pretium. 
            Pellentesque augue mauris, lobortis vel elementum quis, consequat tempor felis. .... 
        </description>
        <problems> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lobortis lacinia
            porttitor.Sed eu nunc ipsum, nec suscipit lectus. Quisque quis nibh at sem dictum
            pretium. Pellentesque augue mauris, lobortis vel elementum quis, consequat tempor felis. ... 
        </problems>
        <solutions>Integer dictum diam id ligula aliquet sed dapibus nibh elementum. Pellentesque
            augue mauris, lobortis vel elementum quis, consequat tempor felis..... 
        </solutions>
        <hours_effort>12</hours_effort>
        <technologies>
            <tech>php</tech>
            <tech>javascript</tech>
            <tech>xml</tech>
        </technologies>
        <source_files>
            <file>
                <name>flickr.php</name>
                <purpose>to fetch flickr photos</purpose>
            </file>
            <file>
                <name>index.html</name>
                <purpose>main page with embedded photos</purpose>
            </file>
        </source_files>
    </individual_component>
    <security_discussion>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod 
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud 
        exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor 
        in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
    </security_discussion>
    <individual_comment>This part was done by me and was even easier. It was all just so easy.
        Surprisingly so. Sed eu nunc ipsum, nec suscipit lectus. Quisque quis nibh at sem dictum
        pretium. Pellentesque augue mauris, lobortis vel elementum quis, consequat tempor felis.
    </individual_comment>
</submission_xml>
<!-- DSA Individual XML File Example, 2025-6 -->
<!-- author: prakash.chatterjee@uwe.ac.uk -->
